apiVersion: v1
kind: Pod
metadata:
  name: server-pod
spec:
  containers:
  - name: http2-server
    image: franckccv/http2_server:latest
    ports:
    - containerPort: 8000   # Replace with the port your server application listens on

